### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by jacovandermolen** [RolandMelkert/LDCadShadowLibrary#1]
Hi Roland,

I like to contribute to this repository.

Jaco

**Comment by RolandMelkert** [comment]
Hello Jaco,

You can do so by making a pull request.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Or mail me the new/changed files.

**Comment by jacovandermolen** [comment]
OK, no clue how this works ☺
I see I can create new files too? Would that work?
Sure I can mail you new files too.

Op do 17 nov. 2022 om 19:32 schreef Roland Melkert ***@***.***
